/**
 * ═══════════════════════════════════════════════════════════════════════════
 * MOCK DATA — IronSite Manager
 *
 * Used as fallback when the backend API is not running.
 * Each section is labeled and maps directly to an API endpoint response.
 * ═══════════════════════════════════════════════════════════════════════════
 */

// ── SITES ────────────────────────────────────────────────────────────────────
// Endpoint: GET /api/sites
// Each site represents a construction job site being monitored.
// Fields: id, name, address, status (active|review), progress (0-100),
//         congestion (low|medium|high), trades count, workers count,
//         frames analyzed, zones[]

export const MOCK_SITES = [
  {
    id: "s1",
    name: "Riverside Tower",
    address: "1400 River Rd, Block C",
    status: "active",          // actively being worked on
    progress: 64,              // 64% complete
    congestion: "high",        // worst congestion level
    trades: 5,                 // 5 different trade crews on site
    workers: 23,               // 23 workers total
    frames: 142,               // 142 video frames analyzed by AI
    last_scan: "12 min ago",
    zones: [
      // Zone A: low activity, single trade — no issues
      { zone: "Zone A — Ground Level West", congestion: 2, trades: ["Concrete"], workers: 4, status: "ok" },
      // Zone B: CRITICAL — 3 trades crammed into same area
      { zone: "Zone B — Level 3 East Scaffolding", congestion: 5, trades: ["Electrical", "Plumbing", "Framing"], workers: 9, status: "critical" },
      // Zone C: moderate concern — crane ops near framing
      { zone: "Zone C — North Exterior", congestion: 3, trades: ["Framing", "Crane Ops"], workers: 6, status: "warning" },
      // Zone D: clear — just deliveries
      { zone: "Zone D — South Parking / Staging", congestion: 1, trades: ["Delivery"], workers: 2, status: "ok" },
      // Zone E: moderate — two trades sharing interior space
      { zone: "Zone E — Level 2 Interior", congestion: 3, trades: ["HVAC", "Electrical"], workers: 5, status: "warning" },
    ],
  },
  {
    id: "s2",
    name: "Harbor Warehouse",
    address: "Dock 9, Industrial Port",
    status: "active",
    progress: 38,
    congestion: "medium",
    trades: 3,
    workers: 14,
    frames: 87,
    last_scan: "1 hr ago",
    zones: [
      { zone: "Zone A — West Bay", congestion: 2, trades: ["Steel Erection"], workers: 5, status: "ok" },
      { zone: "Zone B — East Bay", congestion: 3, trades: ["Concrete", "Plumbing"], workers: 6, status: "warning" },
      // Zone C: logistics problem — delivery blocking access
      { zone: "Zone C — South Access Road", congestion: 4, trades: ["Delivery", "Staging"], workers: 3, status: "critical" },
    ],
  },
  {
    id: "s3",
    name: "Oakfield Homes Ph.2",
    address: "Oakfield Estate, Lots 14-28",
    status: "review",          // in final review phase
    progress: 91,
    congestion: "low",         // no congestion issues
    trades: 2,
    workers: 8,
    frames: 203,
    last_scan: "3 hr ago",
    zones: [
      { zone: "Lots 14-17 — Framing", congestion: 2, trades: ["Framing"], workers: 4, status: "ok" },
      { zone: "Lots 18-21 — Exterior", congestion: 1, trades: ["Cladding"], workers: 3, status: "ok" },
      { zone: "Lots 22-28 — Foundation", congestion: 1, trades: ["Concrete"], workers: 1, status: "ok" },
    ],
  },
]


// ── ALERTS ───────────────────────────────────────────────────────────────────
// Endpoint: GET /api/alerts
// Generated by Safety Agent and Productivity Agent.
// severity: high (red) | medium (yellow) | low (blue)
// source_agent: which AI agent flagged this issue

export const MOCK_ALERTS = [
  {
    id: "a_001",
    site_id: "s1",
    site_name: "Riverside Tower",
    severity: "high",
    source_agent: "productivity",   // flagged by Productivity Agent
    title: "3 trades stacked in Zone B — east scaffolding",
    detail: "Electrical, plumbing, and framing crews all working within the same 400 sq ft area on level 3. Movement corridors are blocked by staged conduit. Recommend staggering electrical to afternoon shift.",
  },
  {
    id: "a_002",
    site_id: "s1",
    site_name: "Riverside Tower",
    severity: "high",
    source_agent: "safety",         // flagged by Safety Agent
    title: "No hard hats detected near crane swing radius",
    detail: "Two workers in the northeast corner are within the crane's operational radius without visible hard hats. This area had the same issue flagged yesterday.",
  },
  {
    id: "a_003",
    site_id: "s2",
    site_name: "Harbor Warehouse",
    severity: "medium",
    source_agent: "productivity",
    title: "Material staging blocking vehicle path",
    detail: "Lumber delivery staged across the main access road on the south side. Prevents equipment from reaching the west bay. Appeared between morning and midday scans.",
  },
  {
    id: "a_004",
    site_id: "s1",
    site_name: "Riverside Tower",
    severity: "low",
    source_agent: "productivity",
    title: "Formwork removal ahead of schedule — level 1",
    detail: "Shores on level 1 east deck are 60% removed, ahead of the projected timeline. Positive progress indicator.",
  },
  {
    id: "a_005",
    site_id: "s3",
    site_name: "Oakfield Homes Ph.2",
    severity: "low",
    source_agent: "productivity",
    title: "Exterior cladding progressing on south units",
    detail: "Facade installation detected on lots 18-21, consistent with expected schedule. No congestion issues in this zone.",
  },
]


// ── BRIEFINGS ────────────────────────────────────────────────────────────────
// Endpoint: GET /api/sites/{site_id}/briefing
// Plain-language AI-generated summaries for non-technical site managers.
// Each briefing ends with a concrete "Recommendation:" line.

export const MOCK_BRIEFINGS = {
  s1:
    "The biggest issue today is Zone B on level 3. Three different crews — electrical, plumbing, and framing — are all trying to work in the same area at the same time. It's packed. Workers can barely move through, and the conduit staged on the floor is blocking the walkway.\n\n" +
    "Compared to yesterday, congestion in Zone B got worse. It was two trades yesterday, now it's three. Zone C near the crane also has a safety concern — two workers spotted without hard hats in the swing radius. This is the second day in a row.\n\n" +
    "The good news: formwork removal on level 1 is running ahead of schedule. The east deck is clearing out faster than expected.\n\n" +
    "Recommendation: Move the electrical crew in Zone B to the afternoon shift so they're not overlapping with framing. Address the hard hat issue in Zone C immediately — it's a repeat violation.",

  s2:
    "Work is moving steadily but there's a logistics problem on the south side. A lumber delivery got staged right across the main access road, which means equipment can't get to the west bay. This showed up between the morning and midday scans — it wasn't there earlier.\n\n" +
    "The east bay has two trades sharing space (concrete and plumbing) but it's manageable for now. No safety flags today.\n\n" +
    "Recommendation: Get the lumber restaged off the access road before the afternoon equipment run. If it stays, the west bay crew will be idle.",

  s3:
    "Everything is running smoothly. Exterior cladding is going up on lots 18 through 21, right on schedule. No congestion anywhere — the crews are well spread out across the site.\n\n" +
    "Compared to last week, we've made good progress. The site is in the final stretch.\n\n" +
    "Recommendation: No action needed. Consider pulling one crew to support Riverside Tower if they can be spared.",
}


// ── LIVE FEEDS ───────────────────────────────────────────────────────────────
// Endpoint: GET /api/streaming/feeds
// Camera feeds: "fixed" = mounted camera, "helmet" = worker helmet cam.
// worker field is null for fixed cameras.

export const MOCK_FEEDS = [
  { id: "cam1", label: "Cam 1 — Crane Top",     site_id: "s1", site_name: "Riverside Tower",  worker: null,          type: "fixed" },
  { id: "cam2", label: "Cam 2 — J. Martinez",   site_id: "s1", site_name: "Riverside Tower",  worker: "J. Martinez", type: "helmet" },
  { id: "cam3", label: "Cam 3 — Level 3 East",  site_id: "s1", site_name: "Riverside Tower",  worker: null,          type: "fixed" },
  { id: "cam4", label: "Cam 4 — R. Chen",       site_id: "s1", site_name: "Riverside Tower",  worker: "R. Chen",     type: "helmet" },
  { id: "cam5", label: "Cam 5 — South Gate",    site_id: "s2", site_name: "Harbor Warehouse", worker: null,          type: "fixed" },
  { id: "cam6", label: "Cam 6 — T. Williams",   site_id: "s2", site_name: "Harbor Warehouse", worker: "T. Williams", type: "helmet" },
]


// ── ZONE DATA (by site) ─────────────────────────────────────────────────────
// Endpoint: GET /api/productivity/report/{site_id}/zones
// congestion: 1 (empty) to 5 (severely congested)
// status: ok | warning | critical

export const MOCK_ZONES = {
  s1: MOCK_SITES[0].zones,
  s2: MOCK_SITES[1].zones,
  s3: MOCK_SITES[2].zones,
}


// ── HELPER: check if backend is reachable ────────────────────────────────────

let _backendAvailable = null

export async function isBackendAvailable() {
  if (_backendAvailable !== null) return _backendAvailable
  try {
    const res = await fetch('/api/sites', { signal: AbortSignal.timeout(1500) })
    _backendAvailable = res.ok
  } catch {
    _backendAvailable = false
  }
  return _backendAvailable
}
