/**
 * ═══════════════════════════════════════════════════════════════════════════
 * MOCK DATA — IronSite Manager
 *
 * Used as fallback when the backend API is not running.
 * Each section is labeled and maps directly to an API endpoint response.
 * ═══════════════════════════════════════════════════════════════════════════
 */

// ── SITES ────────────────────────────────────────────────────────────────────
// Endpoint: GET /api/sites
// Each site represents a construction job site being monitored.
// Fields: id, name, address, status (active|review), progress (0-100),
//         congestion (low|medium|high), trades count, workers count,
//         frames analyzed, zones[]

export const MOCK_SITES = [
  {
    id: "s1",
    name: "Riverside Tower",
    address: "1400 River Rd, Block C",
    status: "active",          // actively being worked on
    progress: 64,              // 64% complete
    congestion: "high",        // worst congestion level
    trades: 5,                 // 5 different trade crews on site
    workers: 23,               // 23 workers total
    frames: 142,               // 142 video frames analyzed by AI
    last_scan: "12 min ago",
    zones: [
      // Zone A: low activity, single trade — no issues
      { zone: "Zone A — Ground Level West", congestion: 2, trades: ["Concrete"], workers: 4, status: "ok" },
      // Zone B: CRITICAL — 3 trades crammed into same area
      { zone: "Zone B — Level 3 East Scaffolding", congestion: 5, trades: ["Electrical", "Plumbing", "Framing"], workers: 9, status: "critical" },
      // Zone C: moderate concern — crane ops near framing
      { zone: "Zone C — North Exterior", congestion: 3, trades: ["Framing", "Crane Ops"], workers: 6, status: "warning" },
      // Zone D: clear — just deliveries
      { zone: "Zone D — South Parking / Staging", congestion: 1, trades: ["Delivery"], workers: 2, status: "ok" },
      // Zone E: moderate — two trades sharing interior space
      { zone: "Zone E — Level 2 Interior", congestion: 3, trades: ["HVAC", "Electrical"], workers: 5, status: "warning" },
    ],
  },
  {
    id: "s2",
    name: "Harbor Warehouse",
    address: "Dock 9, Industrial Port",
    status: "active",
    progress: 38,
    congestion: "medium",
    trades: 3,
    workers: 14,
    frames: 87,
    last_scan: "1 hr ago",
    zones: [
      { zone: "Zone A — West Bay", congestion: 2, trades: ["Steel Erection"], workers: 5, status: "ok" },
      { zone: "Zone B — East Bay", congestion: 3, trades: ["Concrete", "Plumbing"], workers: 6, status: "warning" },
      // Zone C: logistics problem — delivery blocking access
      { zone: "Zone C — South Access Road", congestion: 4, trades: ["Delivery", "Staging"], workers: 3, status: "critical" },
    ],
  },
  {
    id: "s3",
    name: "Oakfield Homes Ph.2",
    address: "Oakfield Estate, Lots 14-28",
    status: "review",
    progress: 91,
    congestion: "low",
    trades: 0,
    workers: 0,
    frames: 0,
    last_scan: "—",
    zones: [],
  },
]


// ── ALERTS ───────────────────────────────────────────────────────────────────
// Endpoint: GET /api/alerts
// Generated by Safety Agent and Productivity Agent.
// severity: high (red) | medium (yellow) | low (blue)
// source_agent: which AI agent flagged this issue

export const MOCK_ALERTS = [
  {
    id: "a_001",
    site_id: "s1",
    site_name: "Riverside Tower",
    severity: "high",
    source_agent: "productivity",   // flagged by Productivity Agent
    title: "3 trades stacked in Zone B — east scaffolding",
    detail: "Electrical, plumbing, and framing crews all working within the same 400 sq ft area on level 3. Movement corridors are blocked by staged conduit. Recommend staggering electrical to afternoon shift.",
  },
  {
    id: "a_002",
    site_id: "s1",
    site_name: "Riverside Tower",
    severity: "high",
    source_agent: "safety",         // flagged by Safety Agent
    title: "No hard hats detected near crane swing radius",
    detail: "Two workers in the northeast corner are within the crane's operational radius without visible hard hats. This area had the same issue flagged yesterday.",
  },
  {
    id: "a_003",
    site_id: "s2",
    site_name: "Harbor Warehouse",
    severity: "medium",
    source_agent: "productivity",
    title: "Material staging blocking vehicle path",
    detail: "Lumber delivery staged across the main access road on the south side. Prevents equipment from reaching the west bay. Appeared between morning and midday scans.",
  },
  {
    id: "a_004",
    site_id: "s1",
    site_name: "Riverside Tower",
    severity: "low",
    source_agent: "productivity",
    title: "Formwork removal ahead of schedule — level 1",
    detail: "Shores on level 1 east deck are 60% removed, ahead of the projected timeline. Positive progress indicator.",
  },
]


// ── BRIEFINGS ────────────────────────────────────────────────────────────────
// Endpoint: GET /api/sites/{site_id}/briefing
// Plain-language AI-generated summaries for non-technical site managers.
// Each briefing ends with a concrete "Recommendation:" line.

export const MOCK_BRIEFINGS = {
  s1:
    "The biggest issue today is Zone B on level 3. Three different crews — electrical, plumbing, and framing — are all trying to work in the same area at the same time. It's packed. Workers can barely move through, and the conduit staged on the floor is blocking the walkway.\n\n" +
    "Compared to yesterday, congestion in Zone B got worse. It was two trades yesterday, now it's three. Zone C near the crane also has a safety concern — two workers spotted without hard hats in the swing radius. This is the second day in a row.\n\n" +
    "The good news: formwork removal on level 1 is running ahead of schedule. The east deck is clearing out faster than expected.\n\n" +
    "Recommendation: Move the electrical crew in Zone B to the afternoon shift so they're not overlapping with framing. Address the hard hat issue in Zone C immediately — it's a repeat violation.",

  s2:
    "Work is moving steadily but there's a logistics problem on the south side. A lumber delivery got staged right across the main access road, which means equipment can't get to the west bay. This showed up between the morning and midday scans — it wasn't there earlier.\n\n" +
    "The east bay has two trades sharing space (concrete and plumbing) but it's manageable for now. No safety flags today.\n\n" +
    "Recommendation: Get the lumber restaged off the access road before the afternoon equipment run. If it stays, the west bay crew will be idle.",

}


// ── LIVE FEEDS ───────────────────────────────────────────────────────────────
// Endpoint: GET /api/streaming/feeds
// Camera feeds: "fixed" = mounted camera, "helmet" = worker helmet cam.
// worker field is null for fixed cameras.

export const MOCK_FEEDS = [
  { id: "cam1", label: "Cam 1 — Crane Top",     site_id: "s1", site_name: "Riverside Tower",  worker: null,          type: "fixed" },
  { id: "cam2", label: "Cam 2 — J. Martinez",   site_id: "s1", site_name: "Riverside Tower",  worker: "J. Martinez", type: "helmet" },
  { id: "cam3", label: "Cam 3 — Level 3 East",  site_id: "s1", site_name: "Riverside Tower",  worker: null,          type: "fixed" },
  { id: "cam4", label: "Cam 4 — R. Chen",       site_id: "s1", site_name: "Riverside Tower",  worker: "R. Chen",     type: "helmet" },
  { id: "cam5", label: "Cam 5 — South Gate",    site_id: "s2", site_name: "Harbor Warehouse", worker: null,          type: "fixed" },
  { id: "cam6", label: "Cam 6 — T. Williams",   site_id: "s2", site_name: "Harbor Warehouse", worker: "T. Williams", type: "helmet" },
]


// ── ZONE DATA (by site) ─────────────────────────────────────────────────────
// Endpoint: GET /api/productivity/report/{site_id}/zones
// congestion: 1 (empty) to 5 (severely congested)
// status: ok | warning | critical

export const MOCK_ZONES = {
  s1: MOCK_SITES[0].zones,
  s2: MOCK_SITES[1].zones,
  s3: [],
}


// ── TIMELINE ENTRIES (by site) ───────────────────────────────────────────────
// Each entry: who logged it, what video was uploaded, and the AI summary of that task.
// source: 'upload' | 'manual' | 'agent'

export const MOCK_TIMELINE = {
  s1: [
    {
      id: "tl_s1_1",
      who: "J. Martinez",
      timestamp: "2025-02-21T14:32:00Z",
      source: "upload",
      video: "zone_b_level3_pm.mp4",
      action: "Uploaded afternoon footage of Level 3 East scaffolding",
      ai_summary: "Zone B congestion worsened since morning. Electrical and framing crews now overlap with plumbing. Three blocked walkways detected. Recommend staggering electrical to 3pm start.",
    },
    {
      id: "tl_s1_2",
      who: "R. Chen",
      timestamp: "2025-02-21T11:15:00Z",
      source: "upload",
      video: "crane_zone_c_morning.mp4",
      action: "Uploaded crane swing zone footage — Zone C north exterior",
      ai_summary: "Two workers without hard hats detected within crane radius for 4+ minutes. Same northeast corner as yesterday's flag. No other PPE violations in frame.",
    },
    {
      id: "tl_s1_3",
      who: "Site Manager",
      timestamp: "2025-02-21T09:00:00Z",
      source: "manual",
      video: null,
      action: "Electrical crew moved to afternoon shift per yesterday's recommendation",
      ai_summary: null,
    },
    {
      id: "tl_s1_4",
      who: "J. Martinez",
      timestamp: "2025-02-20T16:45:00Z",
      source: "upload",
      video: "level1_formwork_eod.mp4",
      action: "End-of-day scan of Level 1 east deck formwork removal",
      ai_summary: "Shoring 60% removed, ahead of schedule by approximately 1.5 days. No workers in hazard zone during removal. Staging area clear.",
    },
  ],
  s2: [
    {
      id: "tl_s2_1",
      who: "T. Williams",
      timestamp: "2025-02-21T12:50:00Z",
      source: "upload",
      video: "south_access_midday.mp4",
      action: "Uploaded south access road footage after midday delivery",
      ai_summary: "Lumber staging confirmed across main vehicle corridor. Access road 80% blocked. Equipment unable to reach west bay. Delivery truck still on site.",
    },
    {
      id: "tl_s2_2",
      who: "Site Manager",
      timestamp: "2025-02-21T08:30:00Z",
      source: "manual",
      video: null,
      action: "Morning walkthrough — east bay concrete pour started on schedule",
      ai_summary: null,
    },
  ],
  s3: [],
}

// ── HELPER: check if backend is reachable ────────────────────────────────────

let _backendAvailable = null

export async function isBackendAvailable() {
  if (_backendAvailable !== null) return _backendAvailable
  try {
    const res = await fetch('/api/sites', { signal: AbortSignal.timeout(1500) })
    _backendAvailable = res.ok
  } catch {
    _backendAvailable = false
  }
  return _backendAvailable
}
